import argparse
import json
import os
from langsmith import Client


def parse_args():
    parser = argparse.ArgumentParser(
        description="Trigger LangSmith Fleet approval workflow"
    )

    parser.add_argument(
        "--review-file",
        required=True,
        help="Path to review-result.json generated by CI"
    )
    parser.add_argument(
        "--pr-number",
        required=True,
        type=int,
        help="Pull request number"
    )

    return parser.parse_args()


def load_review(review_file: str) -> dict:
    if not os.path.exists(review_file):
        raise FileNotFoundError(f"Review file not found: {review_file}")

    with open(review_file, "r") as f:
        return json.load(f)


def trigger_fleet_approval(review_data: dict, pr_number: int):
    """
    Sends PR review output to LangSmith Fleet approval agent.
    The Fleet agent is responsible for:
    - Approval decision logic
    - Notification routing (email / Slack / Teams / Jira)
    - Audit logging
    """

    client = Client()

    result = client.run(
        "pr_approval_orchestration_agent",  # ✅ Fleet agent name
        inputs={
            "pr_number": pr_number,
            "review": review_data,
            "repository": os.environ.get("GITHUB_REPOSITORY"),
            "trigger_source": "github_actions"
        }
    )

    return result


def main():
    args = parse_args()

    review_data = load_review(args.review_file)

    print("🚀 Triggering Fleet approval workflow...")
    fleet_result = trigger_fleet_approval(
        review_data=review_data,
        pr_number=args.pr_number
    )

    # Optional: store Fleet response for audit/debug
    with open("fleet-approval-result.json", "w") as f:
        json.dump(fleet_result, f, indent=2)

    print("✅ Fleet approval workflow triggered successfully")
    print("📄 Fleet response written to fleet-approval-result.json")


if __name__ == "__main__":
    main()
